import type { Locale } from "@/lib/i18n";
export const accountCopy: Record<Locale, { title: string; email: string; send: string; recover: string; intro: string; local: string; sent: string; error: string; signedIn: string; signOut: string; continue: string; legacy: string; pending: string; disabled: string; deleteData: string }> = {
  de: {title:"Mein Konto",email:"E-Mail-Adresse",send:"Anmeldelink erhalten",recover:"Zugang wiederherstellen",intro:"Melde dich mit einem einmaligen Link an oder erstelle ein Konto. Fordere zur Wiederherstellung einen neuen Link an dieselbe E-Mail-Adresse an. Er gilt 10 Minuten.",local:"Lokaler Test: simulierte E-Mail. Dies bestätigt nicht den Besitz eines echten Postfachs. Verwende nur fiktive Daten.",sent:"Link im lokalen Entwicklungspostfach gespeichert. Keine E-Mail wurde versendet. Öffne den Link, um den Test abzuschließen.",error:"Anmeldung nicht abgeschlossen. Fordere einen neuen Link an; der bisherige ist möglicherweise abgelaufen oder bereits verwendet.",signedIn:"Zugang mit Testlink bestätigt",signOut:"Abmelden",continue:"Meine Abrechnungen öffnen",legacy:"Abrechnungen der alten anonymen Sitzung bleiben erhalten, werden diesem Konto aber nicht automatisch zugeordnet.",pending:"Bitte warten…",disabled:"Kontozugang ist außerhalb der lokalen Entwicklung noch nicht eingerichtet.",deleteData:"Abrechnungen und Beschäftigungsprofil meines Kontos löschen"},
  es: { title: "Mi cuenta", email: "Correo electrónico", send: "Recibir enlace de acceso", recover: "Recuperar acceso", intro: "Entra o crea tu cuenta con un enlace de un solo uso. Para recuperar el acceso, solicita otro enlace con el mismo correo. Caduca en 10 minutos.", local: "Prueba local: correo simulado. No acredita la propiedad de un correo real. Usa solo datos ficticios.", sent: "Enlace guardado en el buzón local de desarrollo. No se ha enviado ningún correo. Abre ese enlace para completar la prueba.", error: "No se pudo completar el acceso. Solicita un enlace nuevo; el anterior puede haber caducado o estar utilizado.", signedIn: "Acceso confirmado con enlace de prueba", signOut: "Cerrar sesión", continue: "Ir a Mis nóminas", legacy: "Las nóminas de la antigua sesión anónima se conservan, pero no se asignan automáticamente a esta cuenta.", pending: "Espera…", disabled: "El acceso a cuentas aún no está configurado fuera del entorno local.", deleteData: "Borrar las nóminas y el perfil de mi cuenta" },
  en: { title: "My account", email: "Email address", send: "Get a sign-in link", recover: "Recover access", intro: "Sign in or create an account with a single-use link. To recover access, request another link with the same email. It expires in 10 minutes.", local: "Local test: simulated email. This does not prove ownership of a real mailbox. Use fictional data only.", sent: "Link saved to the local development mailbox. No email was sent. Open that link to complete the test.", error: "Sign-in could not be completed. Request a new link; the previous one may have expired or been used.", signedIn: "Access confirmed using a test link", signOut: "Sign out", continue: "Open My payslips", legacy: "Payslips from the old anonymous session are preserved but are not automatically assigned to this account.", pending: "Please wait…", disabled: "Account access is not yet configured outside local development.", deleteData: "Delete my account's payslips and employment profile" },
  pl: { title: "Moje konto", email: "Adres e-mail", send: "Otrzymaj link logowania", recover: "Odzyskaj dostęp", intro: "Zaloguj się lub utwórz konto za pomocą jednorazowego linku. Aby odzyskać dostęp, poproś o nowy link na ten sam adres. Wygasa po 10 minutach.", local: "Test lokalny: symulowana wiadomość. Nie potwierdza własności prawdziwej skrzynki. Używaj fikcyjnych danych.", sent: "Link zapisano w lokalnej skrzynce deweloperskiej. Nie wysłano wiadomości. Otwórz link, aby zakończyć test.", error: "Nie udało się zalogować. Poproś o nowy link; poprzedni mógł wygasnąć lub zostać użyty.", signedIn: "Dostęp potwierdzony linkiem testowym", signOut: "Wyloguj", continue: "Otwórz moje paski", legacy: "Paski z poprzedniej anonimowej sesji zachowano, ale nie przypisano ich automatycznie do tego konta.", pending: "Czekaj…", disabled: "Konta nie są jeszcze skonfigurowane poza środowiskiem lokalnym.", deleteData: "Usuń paski i profil zatrudnienia mojego konta" },
  pt: { title: "A minha conta", email: "Endereço de email", send: "Receber ligação de acesso", recover: "Recuperar acesso", intro: "Entra ou cria uma conta com uma ligação de utilização única. Para recuperar o acesso, pede outra com o mesmo email. Expira em 10 minutos.", local: "Teste local: email simulado. Não comprova a propriedade de um email real. Usa apenas dados fictícios.", sent: "Ligação guardada na caixa de correio local de desenvolvimento. Não foi enviado email. Abre a ligação para concluir o teste.", error: "Não foi possível entrar. Pede uma nova ligação; a anterior pode ter expirado ou sido usada.", signedIn: "Acesso confirmado com ligação de teste", signOut: "Terminar sessão", continue: "Abrir os meus recibos", legacy: "Os recibos da sessão anónima anterior são conservados, mas não são atribuídos automaticamente a esta conta.", pending: "Aguarda…", disabled: "O acesso a contas ainda não está configurado fora do ambiente local.", deleteData: "Eliminar os recibos e o perfil de emprego da minha conta" },
  lt: { title: "Mano paskyra", email: "El. pašto adresas", send: "Gauti prisijungimo nuorodą", recover: "Atkurti prieigą", intro: "Prisijunkite arba sukurkite paskyrą vienkartine nuoroda. Prieigai atkurti paprašykite kitos nuorodos tuo pačiu el. paštu. Ji galioja 10 minučių.", local: "Vietinis bandymas: imituojamas el. laiškas. Tai nepatvirtina tikros pašto dėžutės nuosavybės. Naudokite išgalvotus duomenis.", sent: "Nuoroda išsaugota vietinėje kūrimo pašto dėžutėje. Laiškas neišsiųstas. Atidarykite nuorodą bandymui užbaigti.", error: "Prisijungti nepavyko. Paprašykite naujos nuorodos; ankstesnė galėjo pasenti arba būti panaudota.", signedIn: "Prieiga patvirtinta bandomąja nuoroda", signOut: "Atsijungti", continue: "Atidaryti mano algalapius", legacy: "Ankstesnio anoniminio seanso algalapiai išsaugoti, bet automatiškai šiai paskyrai nepriskiriami.", pending: "Palaukite…", disabled: "Paskyrų prieiga dar nesukonfigūruota už vietinės aplinkos ribų.", deleteData: "Ištrinti mano paskyros algalapius ir darbo profilį" },
  ro: { title: "Contul meu", email: "Adresă de email", send: "Primește linkul de acces", recover: "Recuperează accesul", intro: "Intră sau creează un cont cu un link de unică folosință. Pentru recuperare, solicită alt link cu același email. Expiră în 10 minute.", local: "Test local: email simulat. Nu dovedește deținerea unei adrese reale. Folosește doar date fictive.", sent: "Link salvat în cutia poștală locală de dezvoltare. Nu s-a trimis niciun email. Deschide linkul pentru a termina testul.", error: "Accesul nu a putut fi finalizat. Solicită un link nou; cel anterior poate fi expirat sau folosit.", signedIn: "Acces confirmat cu link de test", signOut: "Deconectare", continue: "Deschide fluturașii mei", legacy: "Fluturașii sesiunii anonime vechi sunt păstrați, dar nu sunt atribuiți automat acestui cont.", pending: "Așteaptă…", disabled: "Accesul la conturi nu este încă configurat în afara mediului local.", deleteData: "Șterge fluturașii și profilul de angajare ale contului meu" },
  ru: { title: "Моя учётная запись", email: "Электронная почта", send: "Получить ссылку для входа", recover: "Восстановить доступ", intro: "Войдите или создайте учётную запись по одноразовой ссылке. Для восстановления запросите новую ссылку на тот же адрес. Она действует 10 минут.", local: "Локальный тест: имитация письма. Это не подтверждает владение настоящим почтовым ящиком. Используйте вымышленные данные.", sent: "Ссылка сохранена в локальном почтовом ящике разработки. Письмо не отправлялось. Откройте ссылку для завершения теста.", error: "Не удалось войти. Запросите новую ссылку: предыдущая могла истечь или быть использована.", signedIn: "Доступ подтверждён тестовой ссылкой", signOut: "Выйти", continue: "Открыть мои листки", legacy: "Листки старого анонимного сеанса сохранены, но не привязаны автоматически к этой учётной записи.", pending: "Подождите…", disabled: "Вход в учётные записи ещё не настроен вне локальной среды.", deleteData: "Удалить листки и профиль работы моей учётной записи" },
};

export const accountStorageCopy: Record<Locale, string> = {
 de: "Konto: E-Mail-Adresse, zufällige interne Kennung und Anmeldesitzungen. Abrechnungen gehören zu dieser Kennung; PPSN und Mitarbeiternummer dienen nicht als Identität. Abmelden löscht keine Daten.",
 es: "Cuenta: correo electrónico, identificador interno aleatorio y sesiones de acceso. Las nóminas pertenecen a ese identificador; no usamos el PPSN ni el número de empleado como identidad. Cerrar sesión no borra los datos.",
 en: "Account: email address, random internal identifier and sign-in sessions. Payslips belong to that identifier; PPSN and employee numbers are not used as identity. Signing out does not delete data.",
 pl: "Konto: adres e-mail, losowy identyfikator wewnętrzny i sesje logowania. Paski należą do tego identyfikatora; PPSN i numer pracownika nie służą jako tożsamość. Wylogowanie nie usuwa danych.",
 pt: "Conta: email, identificador interno aleatório e sessões de acesso. Os recibos pertencem a esse identificador; não usamos PPSN nem número de funcionário como identidade. Sair não apaga dados.",
 lt: "Paskyra: el. paštas, atsitiktinis vidinis identifikatorius ir prisijungimo seansai. Algalapiai priklauso tam identifikatoriui; PPSN ir darbuotojo numeriai nenaudojami tapatybei. Atsijungimas duomenų neištrina.",
 ro: "Cont: email, identificator intern aleatoriu și sesiuni de acces. Fluturașii aparțin acelui identificator; PPSN și numărul angajatului nu sunt folosite ca identitate. Deconectarea nu șterge datele.",
 ru: "Учётная запись: email, случайный внутренний идентификатор и сеансы входа. Листки принадлежат этому идентификатору; PPSN и номер сотрудника не используются как личность. Выход не удаляет данные.",
};
