import type { Company, DriverReview } from "@/lib/types";

export const companies: Company[] = [
  {
    slug: "swift",
    name: "Swift Transportation",
    shortName: "Swift",
    initials: "SW",
    hue: 28,
    headquarters: "Phoenix, AZ",
    founded: 1966,
    fleetSize: 18000,
    equipment: ["dry-van", "reefer", "flatbed"],
    operations: ["otr", "regional", "dedicated"],
    payType: "cpm",
    advertised: {
      cpm: 0.62,
      milesPerWeek: 3000,
      signOnBonus: 10000,
      claim: "Earn up to $0.62/mile plus a $10,000 sign-on.",
    },
    reported: {
      cpm: 0.47,
      weeklyPay: 1080,
      milesPerWeek: 2300,
      homeTimeDaysOut: 21,
      rating: 2.6,
      reviewCount: 184,
    },
    conditions: {
      detentionPaid: false,
      layoverPaid: true,
      forcedDispatch: true,
      slipSeating: true,
      orientationPaid: false,
      petFriendly: true,
      passengerPolicy: true,
      truckAge: "often 400k+ miles",
      averageHours: 68,
      trainerNote: "Student pay is a cut of the trainer's load, not a wage.",
    },
    summary:
      "Biggest fleet on the board. Recruiters quote top-end CPM after tenure; new drivers report loaded-mile pay, long resets, and trucks that sit.",
  },
  {
    slug: "werner",
    name: "Werner Enterprises",
    shortName: "Werner",
    initials: "WE",
    hue: 210,
    headquarters: "Omaha, NE",
    founded: 1956,
    fleetSize: 8300,
    equipment: ["dry-van", "reefer"],
    operations: ["otr", "regional", "dedicated"],
    payType: "cpm",
    advertised: {
      cpm: 0.58,
      milesPerWeek: 2800,
      signOnBonus: 5000,
      claim: "Up to $0.58 CPM on dedicated and regional freight.",
    },
    reported: {
      cpm: 0.5,
      weeklyPay: 1220,
      milesPerWeek: 2450,
      homeTimeDaysOut: 14,
      rating: 3.1,
      reviewCount: 96,
    },
    conditions: {
      detentionPaid: true,
      layoverPaid: true,
      forcedDispatch: true,
      slipSeating: false,
      orientationPaid: true,
      petFriendly: true,
      passengerPolicy: true,
      truckAge: "mixed, some new Cascadias",
      averageHours: 64,
    },
    summary:
      "Steadier miles than the other megas, but the advertised CPM is the top of a ladder most drivers never climb.",
  },
  {
    slug: "prime",
    name: "Prime Inc.",
    shortName: "Prime",
    initials: "PR",
    hue: 145,
    headquarters: "Springfield, MO",
    founded: 1970,
    fleetSize: 7500,
    equipment: ["reefer", "tanker", "flatbed"],
    operations: ["otr", "regional"],
    payType: "cpm",
    advertised: {
      cpm: 0.65,
      milesPerWeek: 2900,
      signOnBonus: 8000,
      claim: "Reefer and tanker teams can clear $0.65/mile.",
    },
    reported: {
      cpm: 0.57,
      weeklyPay: 1480,
      milesPerWeek: 2600,
      homeTimeDaysOut: 18,
      rating: 3.4,
      reviewCount: 71,
    },
    conditions: {
      detentionPaid: true,
      layoverPaid: true,
      forcedDispatch: false,
      slipSeating: false,
      orientationPaid: true,
      petFriendly: true,
      passengerPolicy: true,
      truckAge: "late-model company trucks",
      averageHours: 66,
      trainerNote: "Lease-purchase pitch starts in orientation.",
    },
    summary:
      "Strong reefer and tanker freight. Solo company drivers do better than the lease-purchase stories circulating on the lot.",
  },
  {
    slug: "schneider",
    name: "Schneider",
    shortName: "Schneider",
    initials: "SC",
    hue: 255,
    headquarters: "Green Bay, WI",
    founded: 1935,
    fleetSize: 10000,
    equipment: ["dry-van", "specialized"],
    operations: ["otr", "regional", "dedicated"],
    payType: "cpm",
    advertised: {
      cpm: 0.6,
      milesPerWeek: 2700,
      signOnBonus: 4000,
      claim: "Predictable dedicated lanes starting at $0.60/mile.",
    },
    reported: {
      cpm: 0.53,
      weeklyPay: 1290,
      milesPerWeek: 2400,
      homeTimeDaysOut: 10,
      rating: 3.5,
      reviewCount: 88,
    },
    conditions: {
      detentionPaid: true,
      layoverPaid: true,
      forcedDispatch: false,
      slipSeating: false,
      orientationPaid: true,
      petFriendly: false,
      passengerPolicy: true,
      truckAge: "generally under 4 years",
      averageHours: 60,
    },
    summary:
      "More process, fewer surprises. Dedicated accounts pay closer to the ad; OTR still bleeds empty miles.",
  },
  {
    slug: "cr-england",
    name: "C.R. England",
    shortName: "C.R. England",
    initials: "CR",
    hue: 12,
    headquarters: "Salt Lake City, UT",
    founded: 1920,
    fleetSize: 4200,
    equipment: ["reefer", "dry-van"],
    operations: ["otr", "regional"],
    payType: "cpm",
    advertised: {
      cpm: 0.55,
      milesPerWeek: 2800,
      signOnBonus: 6000,
      claim: "Paid CDL training and $0.55/mile after graduation.",
    },
    reported: {
      cpm: 0.41,
      weeklyPay: 890,
      milesPerWeek: 2150,
      homeTimeDaysOut: 24,
      rating: 2.3,
      reviewCount: 129,
    },
    conditions: {
      detentionPaid: false,
      layoverPaid: false,
      forcedDispatch: true,
      slipSeating: true,
      orientationPaid: false,
      petFriendly: false,
      passengerPolicy: false,
      truckAge: "high mileage reefers",
      averageHours: 70,
      trainerNote: "Contract buyout if you leave before 10 months.",
    },
    summary:
      "Training mill reputation. The advertised rate is after a long student period; first-year take-home is the real story.",
  },
  {
    slug: "roehl",
    name: "Roehl Transport",
    shortName: "Roehl",
    initials: "RH",
    hue: 195,
    headquarters: "Marshfield, WI",
    founded: 1962,
    fleetSize: 2300,
    equipment: ["dry-van", "flatbed"],
    operations: ["regional", "dedicated"],
    payType: "cpm",
    advertised: {
      cpm: 0.58,
      milesPerWeek: 2500,
      signOnBonus: 3000,
      claim: "Midwest regional runs with real weekends at home.",
    },
    reported: {
      cpm: 0.55,
      weeklyPay: 1360,
      milesPerWeek: 2480,
      homeTimeDaysOut: 5,
      rating: 4.1,
      reviewCount: 54,
    },
    conditions: {
      detentionPaid: true,
      layoverPaid: true,
      forcedDispatch: false,
      slipSeating: false,
      orientationPaid: true,
      petFriendly: true,
      passengerPolicy: true,
      truckAge: "late-model assigned trucks",
      averageHours: 58,
    },
    summary:
      "Smaller fleet, tighter gap. Drivers say the recruiter number is close to the settlement — uncommon on this list.",
  },
  {
    slug: "western-express",
    name: "Western Express",
    shortName: "Western Express",
    initials: "WX",
    hue: 40,
    headquarters: "Nashville, TN",
    founded: 1991,
    fleetSize: 2800,
    equipment: ["dry-van"],
    operations: ["otr"],
    payType: "cpm",
    advertised: {
      cpm: 0.6,
      milesPerWeek: 3000,
      signOnBonus: 12000,
      claim: "$12,000 sign-on and $0.60 a mile from day one.",
    },
    reported: {
      cpm: 0.38,
      weeklyPay: 820,
      milesPerWeek: 2100,
      homeTimeDaysOut: 28,
      rating: 1.9,
      reviewCount: 163,
    },
    conditions: {
      detentionPaid: false,
      layoverPaid: false,
      forcedDispatch: true,
      slipSeating: true,
      orientationPaid: false,
      petFriendly: false,
      passengerPolicy: false,
      truckAge: "tired, frequent breakdowns",
      averageHours: 72,
      trainerNote: "Escrow and equipment charges eat the first month.",
    },
    summary:
      "Largest advertised bonus, widest pay gap. Driver reports cluster around breakdowns, unpaid sitting, and disappearing home time.",
  },
  {
    slug: "knight",
    name: "Knight Transportation",
    shortName: "Knight",
    initials: "KN",
    hue: 230,
    headquarters: "Phoenix, AZ",
    founded: 1990,
    fleetSize: 5600,
    equipment: ["dry-van", "reefer"],
    operations: ["otr", "regional", "dedicated"],
    payType: "cpm",
    advertised: {
      cpm: 0.61,
      milesPerWeek: 2800,
      signOnBonus: 7500,
      claim: "Knight-Swift dedicated lanes up to $0.61 CPM.",
    },
    reported: {
      cpm: 0.54,
      weeklyPay: 1340,
      milesPerWeek: 2500,
      homeTimeDaysOut: 12,
      rating: 3.3,
      reviewCount: 67,
    },
    conditions: {
      detentionPaid: true,
      layoverPaid: true,
      forcedDispatch: true,
      slipSeating: false,
      orientationPaid: true,
      petFriendly: true,
      passengerPolicy: true,
      truckAge: "mixed after the Swift merger",
      averageHours: 62,
    },
    summary:
      "Better assigned trucks than Swift proper. Pay still steps up slowly; dedicated is the only way most drivers hit the ad.",
  },
  {
    slug: "jb-hunt",
    name: "J.B. Hunt",
    shortName: "J.B. Hunt",
    initials: "JB",
    hue: 350,
    headquarters: "Lowell, AR",
    founded: 1961,
    fleetSize: 12000,
    equipment: ["dry-van", "specialized"],
    operations: ["dedicated", "regional", "local"],
    payType: "salary",
    advertised: {
      salary: 90000,
      milesPerWeek: 2200,
      signOnBonus: 5000,
      claim: "Dedicated accounts from $75k to $90k a year.",
    },
    reported: {
      weeklyPay: 1480,
      milesPerWeek: 2100,
      homeTimeDaysOut: 2,
      rating: 3.7,
      reviewCount: 102,
    },
    conditions: {
      detentionPaid: true,
      layoverPaid: true,
      forcedDispatch: false,
      slipSeating: false,
      orientationPaid: true,
      petFriendly: false,
      passengerPolicy: false,
      truckAge: "account-spec, usually new",
      averageHours: 55,
    },
    summary:
      "Salary ads assume a specific account and overtime. Home daily dedicated is the win; Intermodal is a different job.",
  },
  {
    slug: "maverick",
    name: "Maverick Transportation",
    shortName: "Maverick",
    initials: "MV",
    hue: 8,
    headquarters: "Little Rock, AR",
    founded: 1980,
    fleetSize: 1900,
    equipment: ["flatbed"],
    operations: ["regional", "otr"],
    payType: "cpm",
    advertised: {
      cpm: 0.72,
      milesPerWeek: 2500,
      signOnBonus: 4000,
      claim: "Flatbed specialists earning $0.72/mile with tarping pay.",
    },
    reported: {
      cpm: 0.66,
      weeklyPay: 1620,
      milesPerWeek: 2380,
      homeTimeDaysOut: 8,
      rating: 4.3,
      reviewCount: 41,
    },
    conditions: {
      detentionPaid: true,
      layoverPaid: true,
      forcedDispatch: false,
      slipSeating: false,
      orientationPaid: true,
      petFriendly: true,
      passengerPolicy: true,
      truckAge: "new assigned trucks",
      averageHours: 60,
    },
    summary:
      "Harder work, closer numbers. Tarping and straps are extra money that actually shows up on the statement.",
  },
];

export const fleet: Company[] = companies;

export function getCompany(slug: string): Company | undefined {
  return fleet.find((company) => company.slug === slug);
}

export const reviews: DriverReview[] = [
  {
    id: "r-swift-1",
    companySlug: "swift",
    nickname: "OTRMike88",
    role: "Solo van, 18 months",
    tenure: "1–2 years",
    payType: "cpm",
    cpm: 0.46,
    weeklyPay: 1040,
    milesPerWeek: 2250,
    homeTime: "3 weeks out if you fight for it",
    rating: 2,
    title: "The $0.62 is after a year, and only on loaded miles",
    body: "Recruiter sold 3,000 miles a week. I averaged 2,200. Empty miles paid pennies. Detention at Walmart was a story they told in orientation, not a line on the settlement. Truck sat two days in Laredo with no breakdown pay that stuck.",
    pros: ["Always freight", "Pet policy is real"],
    cons: ["Loaded-mile CPM", "Home time is a rumor", "Dispatch will strand you"],
    wouldRecommend: false,
    date: "2026-06-12",
  },
  {
    id: "r-swift-2",
    companySlug: "swift",
    nickname: "LaredoAna",
    role: "Student then solo",
    tenure: "Under a year",
    payType: "cpm",
    cpm: 0.41,
    weeklyPay: 780,
    milesPerWeek: 1900,
    homeTime: "Did not get home in 6 weeks",
    rating: 2,
    title: "Training pay is a cut, not a wage",
    body: "I ran with a trainer for 8 weeks and took home under $400 some weeks. They still advertised the top CPM on the website. Once I was solo the miles were better but the truck was a 2019 with 680k. I left before the contract was up and they billed me.",
    pros: ["They will hire you with a fresh CDL"],
    cons: ["Contract", "Trainer split", "Old iron"],
    wouldRecommend: false,
    date: "2026-03-02",
  },
  {
    id: "r-werner-1",
    companySlug: "werner",
    nickname: "NebraskaPaul",
    role: "Dedicated Midwest",
    tenure: "2–5 years",
    payType: "cpm",
    cpm: 0.54,
    weeklyPay: 1380,
    milesPerWeek: 2550,
    homeTime: "Most weekends",
    rating: 4,
    title: "Dedicated is the only honest number",
    body: "OTR was average. I fought onto a dedicated account out of Omaha and the miles showed up. Detention actually posts if you put the times in the app. Still not the billboard CPM, but I can budget.",
    pros: ["App for detention", "Newer trucks on dedicated", "Benefits exist"],
    cons: ["OTR board is a lottery", "Raise schedule is slow"],
    wouldRecommend: true,
    date: "2026-07-21",
  },
  {
    id: "r-prime-1",
    companySlug: "prime",
    nickname: "ReeferJen",
    role: "Solo reefer",
    tenure: "2–5 years",
    payType: "cpm",
    cpm: 0.58,
    weeklyPay: 1540,
    milesPerWeek: 2650,
    homeTime: "Two weeks out, three days home",
    rating: 4,
    title: "Company truck, ignore the lease pitch",
    body: "Orientation spends a day on lease-purchase. I stayed company and the reefers run. Fuel sensor pay is fair. Home time is tight if you take every load they offer, which is how you hit the advertised miles.",
    pros: ["Late-model trucks", "Consistent reefer freight", "Layover is paid"],
    cons: ["Lease-purchase pressure", "Dispatchers push 14-day turns"],
    wouldRecommend: true,
    date: "2026-05-09",
  },
  {
    id: "r-schneider-1",
    companySlug: "schneider",
    nickname: "BayViewTom",
    role: "Dedicated grocery",
    tenure: "1–2 years",
    payType: "cpm",
    cpm: 0.55,
    weeklyPay: 1320,
    milesPerWeek: 2380,
    homeTime: "Home most weekends",
    rating: 4,
    title: "Boring in a good way",
    body: "They do not promise 3,000 miles and then starve you. The account I am on is appointment freight, so average hours stay under 60. Pets are a no, which knocked a lot of people out of orientation.",
    pros: ["Process", "Newer trucks", "Detention paid"],
    cons: ["No pets", "Raises are calendar-based"],
    wouldRecommend: true,
    date: "2026-04-18",
  },
  {
    id: "r-cre-1",
    companySlug: "cr-england",
    nickname: "SLC_Dan",
    role: "Student / first year",
    tenure: "Under a year",
    payType: "cpm",
    cpm: 0.39,
    weeklyPay: 760,
    milesPerWeek: 2000,
    homeTime: "Asked twice, got it once",
    rating: 1,
    title: "Paid training is the hook",
    body: "I needed a CDL. They paid the school and then owned me. First solo weeks were $600 after they took escrow. Reefer units down, sitting unpaid. The website still said $0.55. Read the contract before you fly to Salt Lake.",
    pros: ["They will train you"],
    cons: ["Contract", "Escrow", "Unpaid sitting", "Miles not there"],
    wouldRecommend: false,
    date: "2026-02-11",
  },
  {
    id: "r-roehl-1",
    companySlug: "roehl",
    nickname: "MarshfieldKate",
    role: "Regional van",
    tenure: "2–5 years",
    payType: "cpm",
    cpm: 0.56,
    weeklyPay: 1405,
    milesPerWeek: 2500,
    homeTime: "Home weekly, for real",
    rating: 5,
    title: "Recruiter number matched my second statement",
    body: "I came from a mega. Here the miles are Midwest, the truck is assigned, and nobody laughs when you say you want Saturday night at home. CPM is not the highest on Truckpay, but what I keep is.",
    pros: ["Home time", "Assigned truck", "Honest miles"],
    cons: ["Winter in Wisconsin", "Have to live in their footprint"],
    wouldRecommend: true,
    date: "2026-08-03",
  },
  {
    id: "r-wx-1",
    companySlug: "western-express",
    nickname: "NashBill",
    role: "OTR van",
    tenure: "Under a year",
    payType: "cpm",
    cpm: 0.36,
    weeklyPay: 740,
    milesPerWeek: 2050,
    homeTime: "Never happened",
    rating: 1,
    title: "Sign-on bonus vanished into escrow and repairs",
    body: "They advertised $12k. I saw maybe $2k after they held escrow and charged me for a DPF that was already clogged. Truck died in Oklahoma. Sat four days. Dispatch said take a bus. I did, and I did not go back.",
    pros: ["They answer the phone to hire you"],
    cons: ["Breakdowns", "Escrow", "Forced dispatch", "Bonus is theater"],
    wouldRecommend: false,
    date: "2026-01-28",
  },
  {
    id: "r-wx-2",
    companySlug: "western-express",
    nickname: "ElPasoRico",
    role: "Solo OTR",
    tenure: "1–2 years",
    payType: "cpm",
    cpm: 0.4,
    weeklyPay: 910,
    milesPerWeek: 2200,
    homeTime: "18–25 days out",
    rating: 2,
    title: "Miles on paper, sitting in real life",
    body: "The load board looks full until you get there and the receiver is closed. No detention. I ran hard and still cleared under a thousand after truck payments they said were optional. They were not optional.",
    pros: ["If you like being left alone, you will be"],
    cons: ["Pay", "Equipment", "Home time"],
    wouldRecommend: false,
    date: "2026-05-30",
  },
  {
    id: "r-knight-1",
    companySlug: "knight",
    nickname: "PHX_Carla",
    role: "Regional Southwest",
    tenure: "1–2 years",
    payType: "cpm",
    cpm: 0.53,
    weeklyPay: 1310,
    milesPerWeek: 2480,
    homeTime: "Every 10–12 days",
    rating: 3,
    title: "Fine if you already have a CDL",
    body: "Not a training company energy, which I wanted. Pay is middle of the pack. After the merger you can feel which terminal still runs like Knight and which one runs like Swift. Ask which terminal before you sign.",
    pros: ["Assigned truck at my terminal", "Detention if you document it"],
    cons: ["Terminal lottery", "Forced dispatch on the extra board"],
    wouldRecommend: true,
    date: "2026-06-25",
  },
  {
    id: "r-jbh-1",
    companySlug: "jb-hunt",
    nickname: "HomeDailyChris",
    role: "Dedicated, home daily",
    tenure: "2–5 years",
    payType: "salary",
    weeklyPay: 1560,
    milesPerWeek: 1900,
    homeTime: "Home every night",
    rating: 4,
    title: "$90k is the account, not the company",
    body: "I am on a dedicated retail account. Salary plus extra days. I do not make the poster number every year but I sleep in my bed. Intermodal friends at the same terminal are a different job with a different mood. Read the bid sheet, not the billboard.",
    pros: ["Home daily", "Predictable check", "New truck"],
    cons: ["Account can disappear", "Overtime is expected"],
    wouldRecommend: true,
    date: "2026-07-08",
  },
  {
    id: "r-mav-1",
    companySlug: "maverick",
    nickname: "StrapAndGo",
    role: "Flatbed regional",
    tenure: "2–5 years",
    payType: "cpm",
    cpm: 0.67,
    weeklyPay: 1680,
    milesPerWeek: 2420,
    homeTime: "Home most weekends",
    rating: 5,
    title: "You will tarp. You will get paid for it.",
    body: "This is not a sit-in-the-van job. The CPM is real and tarping pay is itemized. I came from a mega dry van and my take-home jumped even with fewer miles. They expect you to know how to secure steel. If you do, the gap between the ad and the check is the smallest I have seen.",
    pros: ["Itemized accessorials", "Assigned new trucks", "Dispatchers who ran flatbed"],
    cons: ["Weather work", "Hard on the body"],
    wouldRecommend: true,
    date: "2026-08-14",
  },
  {
    id: "r-prime-2",
    companySlug: "prime",
    nickname: "TankerLuis",
    role: "Tanker, 11 months",
    tenure: "Under a year",
    payType: "cpm",
    cpm: 0.6,
    weeklyPay: 1510,
    milesPerWeek: 2500,
    homeTime: "Two weeks out",
    rating: 3,
    title: "Tanker pays, lease-purchase is a trap",
    body: "They moved me to tanker after a clean reefer stretch. Money is there. I watched three people take the lease and then chase payments when freight slowed in January. Stay company until you can buy a truck without their paper.",
    pros: ["Tanker premium", "Training on hazmat"],
    cons: ["Lease-purchase culture", "Springfield housing is packed"],
    wouldRecommend: true,
    date: "2026-03-19",
  },
  {
    id: "r-roehl-2",
    companySlug: "roehl",
    nickname: "FlatbedWes",
    role: "Flatbed, 3 years",
    tenure: "2–5 years",
    payType: "cpm",
    cpm: 0.54,
    weeklyPay: 1290,
    milesPerWeek: 2300,
    homeTime: "Weekly",
    rating: 4,
    title: "Not the most money. Closest to the pitch.",
    body: "I could make more at Maverick. I stay because they do not move the goalposts. Safety actually means they will let you sit a storm. That does not show up in CPM but it shows up in whether you still have a license.",
    pros: ["Safety culture", "Home time"],
    cons: ["Pay cap is real", "Need to live near a terminal"],
    wouldRecommend: true,
    date: "2026-01-09",
  },
];

export function reviewsFor(slug: string): DriverReview[] {
  return reviews.filter((review) => review.companySlug === slug);
}
