import type { Locale } from "@/lib/i18n";
export const entryCopy: Record<Locale, string[]> = {
  de: ["Interaktiver Entwurf · Beispieldaten · keine Dateien hochgeladen", "Sprachen", "Verfügbare Sprachen", "Dein Lohn, einfach erklärt", "Deine Abrechnung, verständlich.", "Füge deine drei neuesten Lohnabrechnungen deines aktuellen oder letzten Arbeitgebers hinzu. Alle drei müssen vom selben Arbeitgeber stammen, um alle Funktionen von MyTruckPay freizuschalten.", "Meine Abrechnung hinzufügen →", "Hinzufügen. Prüfen. Speichern. Ohne endlose Formulare.", "Demo ausprobieren", "Abrechnung prüfen · Beispiel", "Sind alle Angaben richtig?", "Unternehmen", "Erhaltener Nettolohn (€)", "Beispieldokument · Zeitraum von einer Woche", "Speichern und meinen Bereich öffnen →", "Zurück", "Mein Bereich · Beispiel", "Dein Lohn auf einen Blick.", "Letzter Nettolohn", "Unternehmen", "Abrechnungen zur Freischaltung", "1 von 3", "Du hast 1 von 3 Abrechnungen hinzugefügt. Ergänze deine drei neuesten Abrechnungen desselben Arbeitgebers, um alle Funktionen von MyTruckPay freizuschalten.", "Weitere Abrechnung hinzufügen →", "Zurück zum Start", "Designvorschau · keine echten Daten gespeichert"],
  "es": [
    "Propuesta interactiva · datos ficticios · no sube archivos",
    "Idiomas",
    "Idiomas disponibles",
    "Tu salario, sin complicaciones",
    "Tu nómina, clara.",
    "Añade tus tres últimas nóminas de tu empresa actual o de la última en la que trabajaste. Las tres deben ser de la misma empresa para desbloquear todo lo que ofrece MyTruckPay.",
    "Añadir mi nómina →",
    "Añade. Revisa. Guarda. Sin formularios interminables.",
    "Probar la demo",
    "Revisa tu nómina · ejemplo",
    "¿Está todo bien?",
    "Empresa",
    "Neto cobrado (€)",
    "Documento ficticio · periodo de una semana",
    "Guardar y ver mi espacio →",
    "Volver",
    "Mi espacio · ejemplo",
    "Tu salario, en un vistazo.",
    "Último neto cobrado",
    "Empresa",
    "Nóminas para desbloquear el acceso",
    "1 de 3",
    "Llevas 1 de 3 nóminas. Completa tus tres últimas nóminas de la misma empresa para desbloquear todo lo que ofrece MyTruckPay.",
    "Añadir otra nómina →",
    "Volver al inicio",
    "Vista de diseño · sin guardar datos reales"
  ],
  "en": [
    "Interactive proposal · sample data · no files uploaded",
    "Languages",
    "Available languages",
    "Your pay, made simple",
    "Your payslip, clearly.",
    "Add your three latest payslips from your current or most recent employer. All three must be from the same employer to unlock everything MyTruckPay offers.",
    "Add my payslip →",
    "Add. Review. Save. No endless forms.",
    "Try the demo",
    "Review your payslip · example",
    "Does everything look right?",
    "Company",
    "Net pay received (€)",
    "Sample document · one-week period",
    "Save and view my workspace →",
    "Back",
    "My workspace · example",
    "Your pay at a glance.",
    "Latest net pay",
    "Company",
    "Payslips to unlock access",
    "1 of 3",
    "You have added 1 of 3 payslips. Complete your three latest payslips from the same employer to unlock everything MyTruckPay offers.",
    "Add another payslip →",
    "Back to home",
    "Design preview · no real data saved"
  ],
  "pl": [
    "Interaktywny projekt · przykładowe dane · bez przesyłania plików",
    "Języki",
    "Dostępne języki",
    "Twoje wynagrodzenie bez komplikacji",
    "Twój pasek płacowy, jasno.",
    "Dodaj trzy ostatnie paski płacowe od obecnego lub ostatniego pracodawcy. Wszystkie trzy muszą pochodzić od tego samego pracodawcy, aby odblokować wszystko, co oferuje MyTruckPay.",
    "Dodaj mój pasek płacowy →",
    "Dodaj. Sprawdź. Zapisz. Bez długich formularzy.",
    "Wypróbuj demo",
    "Sprawdź pasek płacowy · przykład",
    "Czy wszystko się zgadza?",
    "Firma",
    "Otrzymane wynagrodzenie netto (€)",
    "Przykładowy dokument · okres jednego tygodnia",
    "Zapisz i otwórz mój panel →",
    "Wstecz",
    "Mój panel · przykład",
    "Twoje wynagrodzenie w skrócie.",
    "Ostatnie wynagrodzenie netto",
    "Firma",
    "Paski płacowe do odblokowania dostępu",
    "1 z 3",
    "Dodano 1 z 3 pasków płacowych. Uzupełnij trzy ostatnie paski od tego samego pracodawcy, aby odblokować wszystko, co oferuje MyTruckPay.",
    "Dodaj kolejny pasek płacowy →",
    "Wróć na początek",
    "Podgląd projektu · bez zapisywania rzeczywistych danych"
  ],
  "pt": [
    "Proposta interativa · dados fictícios · sem envio de ficheiros",
    "Idiomas",
    "Idiomas disponíveis",
    "O teu salário, sem complicações",
    "O teu recibo de vencimento, claro.",
    "Adiciona os teus três últimos recibos de vencimento da empresa atual ou da última onde trabalhaste. Os três devem ser da mesma empresa para desbloquear tudo o que o MyTruckPay oferece.",
    "Adicionar o meu recibo →",
    "Adiciona. Revê. Guarda. Sem formulários intermináveis.",
    "Experimentar a demo",
    "Revê o teu recibo · exemplo",
    "Está tudo correto?",
    "Empresa",
    "Valor líquido recebido (€)",
    "Documento fictício · período de uma semana",
    "Guardar e ver o meu espaço →",
    "Voltar",
    "O meu espaço · exemplo",
    "O teu salário num relance.",
    "Último valor líquido recebido",
    "Empresa",
    "Recibos para desbloquear o acesso",
    "1 de 3",
    "Adicionaste 1 de 3 recibos. Completa os teus três últimos recibos da mesma empresa para desbloquear tudo o que o MyTruckPay oferece.",
    "Adicionar outro recibo →",
    "Voltar ao início",
    "Pré-visualização · sem guardar dados reais"
  ],
  "lt": [
    "Interaktyvus maketas · pavyzdiniai duomenys · failai neįkeliami",
    "Kalbos",
    "Galimos kalbos",
    "Jūsų atlyginimas be rūpesčių",
    "Jūsų algalapis, aiškiai.",
    "Pridėkite tris naujausius dabartinio arba paskutinio darbdavio algalapius. Visi trys turi būti iš to paties darbdavio, kad galėtumėte naudotis visomis MyTruckPay galimybėmis.",
    "Pridėti mano algalapį →",
    "Pridėkite. Patikrinkite. Išsaugokite. Be ilgų formų.",
    "Išbandyti demonstraciją",
    "Patikrinkite algalapį · pavyzdys",
    "Ar viskas teisinga?",
    "Įmonė",
    "Gauta suma į rankas (€)",
    "Pavyzdinis dokumentas · vienos savaitės laikotarpis",
    "Išsaugoti ir peržiūrėti paskyrą →",
    "Atgal",
    "Mano paskyra · pavyzdys",
    "Jūsų atlyginimas vienu žvilgsniu.",
    "Paskutinė gauta suma į rankas",
    "Įmonė",
    "Algalapiai prieigai atrakinti",
    "1 iš 3",
    "Pridėjote 1 iš 3 algalapių. Pridėkite tris naujausius to paties darbdavio algalapius, kad galėtumėte naudotis visomis MyTruckPay galimybėmis.",
    "Pridėti kitą algalapį →",
    "Grįžti į pradžią",
    "Dizaino peržiūra · tikri duomenys neišsaugomi"
  ],
  "ro": [
    "Propunere interactivă · date fictive · fără încărcare de fișiere",
    "Limbi",
    "Limbi disponibile",
    "Salariul tău, fără complicații",
    "Fluturașul tău de salariu, pe înțeles.",
    "Adaugă ultimii trei fluturași de salariu de la angajatorul actual sau de la ultimul angajator. Toți trei trebuie să fie de la același angajator pentru a debloca tot ce oferă MyTruckPay.",
    "Adaugă fluturașul meu →",
    "Adaugă. Verifică. Salvează. Fără formulare interminabile.",
    "Încearcă demo",
    "Verifică fluturașul · exemplu",
    "Este totul corect?",
    "Companie",
    "Salariul net primit (€)",
    "Document fictiv · perioadă de o săptămână",
    "Salvează și vezi spațiul meu →",
    "Înapoi",
    "Spațiul meu · exemplu",
    "Salariul tău dintr-o privire.",
    "Ultimul salariu net primit",
    "Companie",
    "Fluturași pentru deblocarea accesului",
    "1 din 3",
    "Ai adăugat 1 din 3 fluturași. Completează ultimii trei fluturași de la același angajator pentru a debloca tot ce oferă MyTruckPay.",
    "Adaugă alt fluturaș →",
    "Înapoi la început",
    "Previzualizare · fără salvarea datelor reale"
  ],
  "ru": [
    "Интерактивный макет · вымышленные данные · без загрузки файлов",
    "Языки",
    "Доступные языки",
    "Ваша зарплата без сложностей",
    "Ваш расчётный листок — понятно.",
    "Добавьте три последних расчётных листка от нынешнего или последнего работодателя. Все три должны быть от одного работодателя, чтобы открыть все возможности MyTruckPay.",
    "Добавить мой расчётный листок →",
    "Добавьте. Проверьте. Сохраните. Без длинных анкет.",
    "Попробовать демоверсию",
    "Проверьте расчётный листок · пример",
    "Всё верно?",
    "Компания",
    "Получено на руки (€)",
    "Вымышленный документ · период в одну неделю",
    "Сохранить и открыть кабинет →",
    "Назад",
    "Мой кабинет · пример",
    "Ваша зарплата с первого взгляда.",
    "Последняя сумма на руки",
    "Компания",
    "Расчётные листки для открытия доступа",
    "1 из 3",
    "Добавлен 1 из 3 расчётных листков. Добавьте три последних листка от одного работодателя, чтобы открыть все возможности MyTruckPay.",
    "Добавить ещё один листок →",
    "На главную",
    "Предпросмотр · реальные данные не сохраняются"
  ]
};
export const explanationCopy: Record<Locale, string[]> = {
  de: ["Wozu dient MyTruckPay?", "Bewahre deine Lohnabrechnungen an einem Ort auf und prüfe sie. Verfolge deinen Lohn bei aktuellen und früheren Arbeitgebern, behalte deinen Verlauf und vergleiche Transportunternehmen, sobald Daten verfügbar sind."],
  "es": [
    "¿Para qué sirve MyTruckPay?",
    "Guarda y revisa tus nóminas en un solo lugar. Sigue lo que has cobrado en tu empresa actual y en las anteriores, conserva tu historial y compara empresas de transporte cuando haya datos disponibles."
  ],
  "en": [
    "What is MyTruckPay for?",
    "Keep and review your payslips in one place. Track your pay across your current and previous employers, keep your history and compare transport companies when data is available."
  ],
  "pl": [
    "Do czego służy MyTruckPay?",
    "Przechowuj i sprawdzaj paski płacowe w jednym miejscu. Śledź wynagrodzenie u obecnych i poprzednich pracodawców, zachowuj historię i porównuj firmy transportowe, gdy dostępne są dane."
  ],
  "pt": [
    "Para que serve o MyTruckPay?",
    "Guarda e revê os teus recibos num só lugar. Acompanha o que recebeste na empresa atual e nas anteriores, conserva o teu histórico e compara empresas de transporte quando existirem dados."
  ],
  "lt": [
    "Kam skirtas MyTruckPay?",
    "Saugokite ir peržiūrėkite algalapius vienoje vietoje. Stebėkite dabartinių ir ankstesnių darbdavių mokėtą atlyginimą, išsaugokite istoriją ir palyginkite transporto įmones, kai yra duomenų."
  ],
  "ro": [
    "La ce folosește MyTruckPay?",
    "Păstrează și verifică fluturașii de salariu într-un singur loc. Urmărește veniturile de la angajatorii actuali și anteriori, păstrează istoricul și compară companiile de transport când există date."
  ],
  "ru": [
    "Для чего нужен MyTruckPay?",
    "Храните и проверяйте расчётные листки в одном месте. Следите за выплатами нынешних и прежних работодателей, сохраняйте историю и сравнивайте транспортные компании при наличии данных."
  ]
};
export const demoCopy: Record<Locale, string[]> = {
  de: ["Demo · Beispieldaten", "Hier geht es los.", "Dies sind drei Beispielabrechnungen desselben Unternehmens. Zum Ausprobieren musst du keine Dokumente hochladen.", "Fiktives Unternehmen: Transportes Demo", "Abrechnung 1 · Woche 1", "Abrechnung 2 · Woche 2", "Abrechnung 3 · Woche 3", "3 von 3 · Beispiel-Nettobeträge", "Freigeschaltete Demo öffnen →", "Zurück zum Start", "Dein Bereich ist freigeschaltet.", "So könnte dein Bereich mit drei Abrechnungen aussehen. Alle Daten und Stellenangebote dieser Demo sind fiktiv.", "Meine Abrechnungen · 3 gespeichert", "Gesamtnetto · drei Wochen", "Durchschnittlicher Nettolohn pro Woche", "Unternehmen · Beispiel", "Deine drei Abrechnungen gehören zu diesem Unternehmen.", "Stellenangebote · in der Demo freigeschaltet", "Fahrer · Transportes Demo", "Fiktives Angebot zur Veranschaulichung. Bewerbungen werden nicht angenommen.", "Demo verlassen"],
  "es": [
    "Demostración · datos ficticios",
    "Así empiezas.",
    "Estas son tres nóminas de ejemplo de una misma empresa. No necesitas subir documentos para probarlo.",
    "Empresa ficticia: Transportes Demo",
    "Nómina 1 · semana 1",
    "Nómina 2 · semana 2",
    "Nómina 3 · semana 3",
    "3 de 3 · importes netos ficticios",
    "Entrar en la demo desbloqueada →",
    "Volver al inicio",
    "Tu espacio, desbloqueado.",
    "Así podría verse tu espacio con las tres nóminas. Ningún dato ni oferta de esta demo es real.",
    "Mis nóminas · 3 guardadas",
    "Total neto · tres semanas",
    "Media neta semanal",
    "Empresas · ejemplo",
    "Tus tres nóminas pertenecen a esta empresa.",
    "Trabajos · acceso desbloqueado en la demo",
    "Conductor/a · Transportes Demo",
    "Oferta ficticia para mostrar el recorrido. No admite candidaturas.",
    "Salir de la demo"
  ],
  "en": [
    "Demo · sample data",
    "Start here.",
    "These are three sample payslips from the same company. You do not need to upload documents to try it.",
    "Fictional company: Transportes Demo",
    "Payslip 1 · week 1",
    "Payslip 2 · week 2",
    "Payslip 3 · week 3",
    "3 of 3 · sample net amounts",
    "Enter the unlocked demo →",
    "Back to home",
    "Your workspace, unlocked.",
    "This is how your workspace could look with three payslips. No data or job offer in this demo is real.",
    "My payslips · 3 saved",
    "Total net pay · three weeks",
    "Average weekly net pay",
    "Companies · example",
    "Your three payslips belong to this company.",
    "Jobs · access unlocked in the demo",
    "Driver · Transportes Demo",
    "Fictional offer to demonstrate the flow. Applications are not accepted.",
    "Exit demo"
  ],
  "pl": [
    "Demo · przykładowe dane",
    "Zacznij tutaj.",
    "To trzy przykładowe paski płacowe z tej samej firmy. Aby wypróbować demo, nie musisz przesyłać dokumentów.",
    "Fikcyjna firma: Transportes Demo",
    "Pasek 1 · tydzień 1",
    "Pasek 2 · tydzień 2",
    "Pasek 3 · tydzień 3",
    "3 z 3 · przykładowe kwoty netto",
    "Otwórz odblokowane demo →",
    "Wróć na początek",
    "Twój panel, odblokowany.",
    "Tak może wyglądać panel z trzema paskami płacowymi. Dane i oferty w tym demo są fikcyjne.",
    "Moje paski płacowe · zapisano 3",
    "Suma netto · trzy tygodnie",
    "Średnia tygodniowa netto",
    "Firmy · przykład",
    "Twoje trzy paski płacowe pochodzą z tej firmy.",
    "Praca · dostęp odblokowany w demo",
    "Kierowca · Transportes Demo",
    "Fikcyjna oferta pokazująca działanie. Nie można aplikować.",
    "Wyjdź z demo"
  ],
  "pt": [
    "Demonstração · dados fictícios",
    "Começa aqui.",
    "São três recibos de exemplo da mesma empresa. Não precisas de enviar documentos para experimentar.",
    "Empresa fictícia: Transportes Demo",
    "Recibo 1 · semana 1",
    "Recibo 2 · semana 2",
    "Recibo 3 · semana 3",
    "3 de 3 · valores líquidos fictícios",
    "Entrar na demo desbloqueada →",
    "Voltar ao início",
    "O teu espaço, desbloqueado.",
    "Assim poderia ser o teu espaço com três recibos. Nenhum dado ou oferta desta demo é real.",
    "Os meus recibos · 3 guardados",
    "Total líquido · três semanas",
    "Média líquida semanal",
    "Empresas · exemplo",
    "Os teus três recibos pertencem a esta empresa.",
    "Empregos · acesso desbloqueado na demo",
    "Motorista · Transportes Demo",
    "Oferta fictícia para mostrar o percurso. Não aceita candidaturas.",
    "Sair da demo"
  ],
  "lt": [
    "Demonstracija · pavyzdiniai duomenys",
    "Pradėkite čia.",
    "Tai trys tos pačios įmonės algalapių pavyzdžiai. Norint išbandyti, dokumentų įkelti nereikia.",
    "Išgalvota įmonė: Transportes Demo",
    "Algalapis 1 · savaitė 1",
    "Algalapis 2 · savaitė 2",
    "Algalapis 3 · savaitė 3",
    "3 iš 3 · pavyzdinės sumos į rankas",
    "Atidaryti atrakintą demonstraciją →",
    "Grįžti į pradžią",
    "Jūsų paskyra atrakinta.",
    "Taip galėtų atrodyti paskyra su trimis algalapiais. Šios demonstracijos duomenys ir darbo pasiūlymai nėra tikri.",
    "Mano algalapiai · išsaugoti 3",
    "Iš viso į rankas · trys savaitės",
    "Savaitės vidurkis į rankas",
    "Įmonės · pavyzdys",
    "Visi trys algalapiai yra iš šios įmonės.",
    "Darbas · prieiga atrakinta demonstracijoje",
    "Vairuotojas · Transportes Demo",
    "Išgalvotas pasiūlymas veikimui parodyti. Kandidatuoti negalima.",
    "Išeiti iš demonstracijos"
  ],
  "ro": [
    "Demonstrație · date fictive",
    "Începe aici.",
    "Aceștia sunt trei fluturași demonstrativi de la aceeași companie. Nu trebuie să încarci documente pentru a încerca.",
    "Companie fictivă: Transportes Demo",
    "Fluturaș 1 · săptămâna 1",
    "Fluturaș 2 · săptămâna 2",
    "Fluturaș 3 · săptămâna 3",
    "3 din 3 · sume nete fictive",
    "Intră în demo deblocat →",
    "Înapoi la început",
    "Spațiul tău, deblocat.",
    "Așa ar putea arăta spațiul tău cu trei fluturași. Datele și ofertele din demo nu sunt reale.",
    "Fluturașii mei · 3 salvați",
    "Total net · trei săptămâni",
    "Media netă săptămânală",
    "Companii · exemplu",
    "Cei trei fluturași provin de la această companie.",
    "Locuri de muncă · acces deblocat în demo",
    "Șofer · Transportes Demo",
    "Ofertă fictivă pentru demonstrație. Nu se acceptă candidaturi.",
    "Ieși din demo"
  ],
  "ru": [
    "Демонстрация · вымышленные данные",
    "Начните здесь.",
    "Это три примера расчётных листков от одной компании. Для демонстрации не нужно загружать документы.",
    "Вымышленная компания: Transportes Demo",
    "Листок 1 · неделя 1",
    "Листок 2 · неделя 2",
    "Листок 3 · неделя 3",
    "3 из 3 · вымышленные суммы на руки",
    "Открыть разблокированную демоверсию →",
    "На главную",
    "Ваш кабинет разблокирован.",
    "Так может выглядеть кабинет с тремя листками. Данные и вакансии в демоверсии вымышлены.",
    "Мои расчётные листки · сохранено 3",
    "Всего на руки · три недели",
    "В среднем на руки за неделю",
    "Компании · пример",
    "Все три листка относятся к этой компании.",
    "Работа · доступ открыт в демоверсии",
    "Водитель · Transportes Demo",
    "Вымышленная вакансия для демонстрации. Отклики не принимаются.",
    "Выйти из демоверсии"
  ]
};
export const historyCopy: Record<Locale, string[]> = {
  de: ["Verlauf nach Arbeitgeber", "Aktueller Arbeitgeber", "Früherer Arbeitgeber", "Gespeicherte Abrechnungen", "Letzte Abrechnung", "Fortschritt zur Freischaltung", "von", "Vervollständige drei Abrechnungen desselben Arbeitgebers. Frühere Abrechnungen bleiben im Verlauf.", "Zugang in dieser Demo freigeschaltet", "Beispielabrechnung hinzufügen", "Fortschritt ab 1 von 3 ausprobieren", "Beispieldaten · keine echten Dokumente gespeichert", "Beschäftigungszeitraum", "heute", "Abrechnungen anzeigen", "Abrechnungen ausblenden", "Noch keine Abrechnungen"],
  "es": [
    "Historial por empresa",
    "Empresa actual",
    "Empresa anterior",
    "Nóminas guardadas",
    "Última nómina",
    "Progreso de acceso",
    "de",
    "Completa tres nóminas de la misma empresa. Las anteriores se conservan en tu historial.",
    "Acceso desbloqueado en esta demostración",
    "Añadir nómina de ejemplo",
    "Probar el progreso desde 1 de 3",
    "Datos ficticios · no se guardan documentos reales",
    "Periodo trabajado",
    "actualidad",
    "Ver nóminas",
    "Ocultar nóminas",
    "Sin nóminas todavía"
  ],
  "en": [
    "History by employer",
    "Current employer",
    "Previous employer",
    "Saved payslips",
    "Latest payslip",
    "Access progress",
    "of",
    "Complete three payslips from the same employer. Earlier ones remain in your history.",
    "Access unlocked in this demo",
    "Add a sample payslip",
    "Try progress from 1 of 3",
    "Sample data · no real documents saved",
    "Employment period",
    "present",
    "View payslips",
    "Hide payslips",
    "No payslips yet"
  ],
  "pl": [
    "Historia według pracodawcy",
    "Obecny pracodawca",
    "Poprzedni pracodawca",
    "Zapisane paski płacowe",
    "Ostatni pasek",
    "Postęp dostępu",
    "z",
    "Dodaj trzy paski od tego samego pracodawcy. Wcześniejsze pozostaną w historii.",
    "Dostęp odblokowany w demonstracji",
    "Dodaj przykładowy pasek",
    "Wypróbuj postęp od 1 z 3",
    "Dane przykładowe · bez zapisywania dokumentów",
    "Okres zatrudnienia",
    "obecnie",
    "Zobacz paski",
    "Ukryj paski",
    "Brak pasków płacowych"
  ],
  "pt": [
    "Histórico por empresa",
    "Empresa atual",
    "Empresa anterior",
    "Recibos guardados",
    "Último recibo",
    "Progresso do acesso",
    "de",
    "Completa três recibos da mesma empresa. Os anteriores ficam no teu histórico.",
    "Acesso desbloqueado nesta demonstração",
    "Adicionar recibo de exemplo",
    "Experimentar o progresso desde 1 de 3",
    "Dados fictícios · sem guardar documentos reais",
    "Período de trabalho",
    "atualidade",
    "Ver recibos",
    "Ocultar recibos",
    "Ainda não há recibos"
  ],
  "lt": [
    "Istorija pagal darbdavį",
    "Dabartinis darbdavys",
    "Ankstesnis darbdavys",
    "Išsaugoti algalapiai",
    "Naujausias algalapis",
    "Prieigos eiga",
    "iš",
    "Pridėkite tris to paties darbdavio algalapius. Ankstesni lieka istorijoje.",
    "Prieiga atrakinta šioje demonstracijoje",
    "Pridėti algalapio pavyzdį",
    "Išbandyti eigą nuo 1 iš 3",
    "Pavyzdiniai duomenys · dokumentai neišsaugomi",
    "Darbo laikotarpis",
    "dabar",
    "Rodyti algalapius",
    "Slėpti algalapius",
    "Algalapių dar nėra"
  ],
  "ro": [
    "Istoric pe angajatori",
    "Angajator actual",
    "Angajator anterior",
    "Fluturași salvați",
    "Ultimul fluturaș",
    "Progresul accesului",
    "din",
    "Completează trei fluturași de la același angajator. Cei anteriori rămân în istoric.",
    "Acces deblocat în această demonstrație",
    "Adaugă un fluturaș de exemplu",
    "Încearcă progresul de la 1 din 3",
    "Date fictive · fără salvarea documentelor reale",
    "Perioada lucrată",
    "prezent",
    "Vezi fluturașii",
    "Ascunde fluturașii",
    "Încă nu există fluturași"
  ],
  "ru": [
    "История по работодателям",
    "Нынешний работодатель",
    "Предыдущий работодатель",
    "Сохранённые листки",
    "Последний листок",
    "Прогресс доступа",
    "из",
    "Добавьте три листка от одного работодателя. Предыдущие останутся в истории.",
    "Доступ открыт в этой демонстрации",
    "Добавить пример листка",
    "Попробовать прогресс с 1 из 3",
    "Вымышленные данные · документы не сохраняются",
    "Период работы",
    "настоящее время",
    "Показать листки",
    "Скрыть листки",
    "Листков пока нет"
  ]
};
export const choiceCopy: Record<Locale, string[]> = {
  de: ["Meine echte Abrechnung hinzufügen", "Meine Demo-Abrechnung hinzufügen", "Öffnet das Formular der lokalen Anwendung.", "Mit Beispieldaten ausprobieren, ohne Dokumente hochzuladen."],
  "es": [
    "Añadir mi nómina de verdad",
    "Añadir mi nómina demo",
    "Abre el formulario de la aplicación local.",
    "Prueba con datos ficticios, sin subir documentos."
  ],
  "en": [
    "Add my real payslip",
    "Add my demo payslip",
    "Opens the local application form.",
    "Try sample data without uploading documents."
  ],
  "pl": [
    "Dodaj mój prawdziwy pasek",
    "Dodaj pasek demonstracyjny",
    "Otwiera formularz aplikacji lokalnej.",
    "Wypróbuj fikcyjne dane bez przesyłania dokumentów."
  ],
  "pt": [
    "Adicionar o meu recibo real",
    "Adicionar o meu recibo demo",
    "Abre o formulário da aplicação local.",
    "Experimenta dados fictícios sem enviar documentos."
  ],
  "lt": [
    "Pridėti tikrą algalapį",
    "Pridėti demonstracinį algalapį",
    "Atidaro vietinės programos formą.",
    "Išbandykite pavyzdinius duomenis neįkeldami dokumentų."
  ],
  "ro": [
    "Adaugă fluturașul meu real",
    "Adaugă fluturașul meu demo",
    "Deschide formularul aplicației locale.",
    "Încearcă date fictive fără să încarci documente."
  ],
  "ru": [
    "Добавить настоящий листок",
    "Добавить демонстрационный листок",
    "Открывает форму локального приложения.",
    "Попробуйте вымышленные данные без загрузки документов."
  ]
};
