"use client";
import { useEffect, useState } from 'react';
import { useT } from './language-provider';
type Entry={id:string;revision:string;company_name:string;rating:number;body:string;reason:string};
export function ModerationQueue(){
 const {locale}=useT();const es=locale==='es';const c=(a:string,b:string)=>es?a:b;
 const [rows,setRows]=useState<Entry[]|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [reload,setReload]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch('/api/moderation/opinions',{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error('load');setRows((await response.json()).opinions);setError('');}).catch(error=>{if(error.name!=='AbortError')setError(es?'No se pudo cargar la bandeja.':'Could not load the queue.');});return()=>controller.abort();},[reload,es]);
 async function decide(row:Entry,status:'approved'|'rejected'){
  setBusy(row.id);setError('');try{const response=await fetch('/api/moderation/opinions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,revision:row.revision,status})});if(response.status===409){setReload(value=>value+1);throw Error('stale');}if(!response.ok)throw Error('save');setRows(current=>current?.filter(item=>item.id!==row.id)??null);}catch(error){setError(error instanceof Error&&error.message==='stale'?c('El comentario cambió. Revisa la versión actual.','The review changed. Check the current version.'):c('No se pudo guardar la decisión.','Could not save the decision.'));}finally{setBusy('');}
 }
 const reasons:Record<string,string>={contact_or_link:c('Posibles datos personales o enlaces','Possible personal data or links'),abuse_or_threat:c('Posible abuso o amenaza','Possible abuse or threat'),sensitive_claim:c('Afirmaciones delicadas','Sensitive claims'),manual_review:c('Revisión manual','Manual review')};
 return <main className="mx-auto max-w-3xl space-y-5 px-4 py-8"><h1 className="font-heading text-3xl font-semibold">{c('Revisar comentarios','Review comments')}</h1><p className="text-sm text-muted-foreground">{c('Lee el texto completo. Una crítica negativa no es motivo para rechazarla. Aprobar no verifica los hechos.','Read the full text. A negative review is not a reason to reject it. Approval does not verify the claims.')}</p>{error&&<p role="alert">{error}</p>}<button onClick={()=>setReload(value=>value+1)} className="min-h-11 rounded-lg border px-4">{c('Actualizar','Refresh')}</button>{rows===null?<p>{c('Cargando…','Loading…')}</p>:rows.length===0?<p>{c('No hay comentarios pendientes.','No pending comments.')}</p>:rows.map(row=><article key={row.id+row.revision} className="space-y-3 rounded-xl border bg-card p-5"><h2 className="text-xl font-semibold">{row.company_name} · {row.rating}/5</h2><p className="text-sm text-muted-foreground">{reasons[row.reason]??row.reason}</p><p className="whitespace-pre-wrap break-words">{row.body}</p><div className="flex gap-3"><button disabled={!!busy} onClick={()=>decide(row,'approved')} className="min-h-11 rounded-lg bg-primary px-4 text-primary-foreground disabled:opacity-50">{c('Publicar','Publish')}</button><button disabled={!!busy} onClick={()=>decide(row,'rejected')} className="min-h-11 rounded-lg border px-4 disabled:opacity-50">{c('No publicar','Do not publish')}</button></div></article>)}</main>;
}
